version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_network

  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
      PS_DOMAIN: localhost:8080
    volumes:
      - prestashop_data:/var/www/html
      - ./modules/dynamicmargin:/var/www/html/modules/dynamicmargin
    networks:
      - prestashop_network

volumes:
  db_data:
  prestashop_data:

networks:
  prestashop_network: